### ISSUE TITLE
November 21 2015 NodeSchool

### ISSUE THREAD

**Issue by lvivier** [nodeschool/vancouver#24]
Time to start planning another school! cc @gyaresu @lrlna @sintaxi @bmann 
## When & Where

Saturday November 21st 12-4pm

Zillow
#460 - 1122 Mainland St

Vancouver
## Tasks
- [x] Date and venue
- [ ] Decide on a theme
- ~~Print hexdex stickers~~ <sup>_next time_</sup>
- [ ] Buy name stickers
- [x] Set up [ti.to](https://ti.to/) event
- [x] Add event to nodeschool.io
- [x] Update README.md
- [x] Update gh-pages
- [x] Call for mentors
- [ ] Send a message to mailing list

**Comment by lrlna** [comment]
Hellooo! November 21st is awesome. What's everyone thinking for the theme?
o.O

**Comment by lvivier** [comment]
@lrlna at the last event we talked about focusing on one of the "Elective" workshoppers as a theme. I thought someone could give a short preso on the topic in the conference room and then we could work through it as a group, or something like that. `functional-javascript-workshop` or `learnyoumongo` might be fun to start with, or `expressworks`?

**Comment by lrlna** [comment]
@lvivier oooo! That's brilliant. I think doing a `functional-javascript-workshop` would be super fun. I think people often forget how functional javascript actually is!

**Comment by lrlna** [comment]
`Make Me Hapi` would actually be a good one to start with if we are doing frameworks. It's easier to understand then express imo. With the next workshops, we can progress to `learnyoumongo` and `expressworks`.

**Comment by Qard** [comment]
@Fishrock123 Any idea when you might be in Vancouver again? Interested in helping with `expressworks`?

**Comment by Fishrock123** [comment]
@Qard probably not until sometime next year. :/

**Comment by misterdjules** [comment]
Looking forward to this one!

@lvivier The `When & Where` section in the description of this issue still mentions the date of the _previous_ meeting, `Sunday October 25th 12-4pm`

@lvivier @lrlna I like all of these ideas and would like to work through any of these workshops.

One thing that I mentioned last time and that might be interesting is to have a short period for show & tell when people could show how they solved each exercise (one different person for each exercise) and people could suggest improvements or other ways to solve the same problem, or just share some of their knowledge on topics related to each exercise.

The goal would be to increase communication and knowledge sharing within the group of attendees, not to make people feel uncomfortable, which can be a challenge. It might also be difficult to keep that within tight time constraints.

**Comment by lvivier** [comment]
@misterdjules yes it does. I am not so smart!

I like the show and tell idea. At the August NodeSchool, those of us in the "learnyounode room" took turns with the HDMI input to the big TV, showing their solution to each problem as they worked through it. Everyone was free to participate in the "group pairing" or work on their own.

**Comment by Qard** [comment]
@Fishrock123 No worries. Whenever you're in the area us node school folks would be happy to have you join us. :smile_cat:

**Comment by lvivier** [comment]
**Call for mentors!** If you can make it to this event, please head over to the [signup page](https://ti.to/nodeschool-vancouver/2015-11-21) and put yourself down as a mentor.

**Comment by lrlna** [comment]
done! @lvivier

**Comment by misterdjules** [comment]
@lvivier Done!

**Comment by lrlna** [comment]
Folks! Should we start tweeting about it?

**Comment by lvivier** [comment]
@lrlna I created a [@nodeschoolyvr](https://twitter.com/nodeschoolyvr) account, but I'm at the Zillow/Retsly hackathon in SF so I haven't had time to flesh it out :disappointed:. I say go ahead and start tweeting! :mega:

**Comment by Qard** [comment]
Yes! Tweet stuff lots!

**Comment by JimFung** [comment]
if there is no set topic yet, can I suggest 'Promises' or 'Functional Programming' as one of the topics?

**Comment by Qard** [comment]
Functional programming would be neat. :)

**Comment by JimFung** [comment]
Mentioned functional programming because I feel like I know enough to be mildly helpful as a mentor haha

**Comment by misterdjules** [comment]
Unfortunately I won't be able to make it today :( Have fun and I hope to see you next time!
