### ISSUE TITLE
January 16, 2016 NodeSchool

### ISSUE THREAD

**Issue by lvivier** [nodeschool/vancouver#27]
Time to start planning another school! cc @gyaresu @lrlna @sintaxi @bmann 
## When & Where

Saturday January 16th 12-4pm

Zillow
#460 - 1122 Mainland St

Vancouver
## Tasks
- [x] Date and venue
- [x] Decide on a theme ([Level Me Up Scotty!](https://github.com/workshopper/levelmeup))
- [ ] Print hexdex stickers
- [ ] Buy name stickers
- [x] Set up [ti.to](https://ti.to/) event ([here](https://ti.to/nodeschool-vancouver/2016-01-16))
- [x] Add event to nodeschool.io
- [x] Update README.md
- [x] Update gh-pages
- [ ] Call for mentors
- [ ] Send a message to mailing list
- [x] Tweet about the upcoming event

**Comment by gyaresu** [comment]
I'm out until late 2016. 
Just wanted to say how much I enjoy our monthly code club. 

Thanks to everyone and have a great year!

Now would be a great time to volunteer a little time to make it a continued success!

Thanks G

**Comment by bitbangr** [comment]
Just a FYI - Jan 15 2016 is a Friday.

**Comment by lvivier** [comment]
@bitbangr yes it is…should be January 16

**Comment by Qard** [comment]
I'll be there! :smile_cat:

**Comment by willhoag** [comment]
Yep I'll be there too!

**Comment by lrlna** [comment]
Will be there!

**Comment by lrlna** [comment]
Oh I also wanted to ask about who handled our twitter? It's been a bit quiet and I thought I would volunteer to tweet every so often 😆👌❇

**Comment by lvivier** [comment]
@lrlna I created the account but I haven't done much with it. DM me and I'll send you the password!

**Comment by lvivier** [comment]
Anyone have ideas for a [theme workshopper](http://nodeschool.io/#workshoppers)? Last time we did Functional JS. [Level Me Up Scotty!](https://github.com/workshopper/levelmeup) gets my vote, or ExpressWorks.

**Comment by JimFung** [comment]
Level Me up Scotty or Learnyoureact both sound good to me

**Comment by lrlna** [comment]
Level Me Up Scotty seems awesome haha
I want to do one on couchdb one of next times too. But thats's probably for February or something.

**Comment by sam-github** [comment]
I might be able to make this a couple of hours of this, though not four.

**Comment by Qard** [comment]
:+1: for Level Me Up. It's got callbacks, streams and module composition; lots of great concepts to learn about in there. :smile_cat:

**Comment by JimFung** [comment]
so any update on the stickers?

**Comment by lrlna** [comment]
ahahhahaha @JimFung .

but I agree, v important.

**Comment by lrlna** [comment]
:tada: :star2: Y'ALL MY ADA FRUIT TOYS ARRIVED TODAY. DO YOU KNOW WHAT THIS MEANS?!?! :star2: :tada:

**Comment by willhoag** [comment]
Oh! Uh, fun! npm install -g nodebot-workshop?!? I got some AdaFruit fun too, but it hasn't arrived.

**Comment by willhoag** [comment]
Can't make it today because sickness has got me down. Wish I could be there. Have fun all!
