### ISSUE TITLE
February 20, 2016 NodeSchool

### ISSUE THREAD

**Issue by lvivier** [nodeschool/vancouver#31]
Event planning time!
## When & Where

Saturday February 20th 12-4pm

Zillow
#460 - 1122 Mainland St

Vancouver
## Tasks
- [x] Date and venue
- [ ] Call for mentors
- [x] Decide on a theme
- [x] Set up [ti.to](https://ti.to/) event ([here](https://ti.to/nodeschool-vancouver/2016-02-20))
- [x] Add event to nodeschool.io
- [ ] Update README.md
- [ ] Update gh-pages
- [ ] Send a message to mailing list
- [x] Tweet about the upcoming event

**Comment by Qard** [comment]
:tada:

**Comment by lrlna** [comment]
:tada: :sparkles:

**Comment by lrlna** [comment]
i should tweet-ask what people want to do this time! _audience participation_

**Comment by forivall** [comment]
iirc, there was some interest in generators.

**Comment by JimFung** [comment]
I'd be interested in learning about generators(or more about es6 in general Did you know computed keys are a thing! that's amazing!!) or react. I've stepped through a few of the react stuff though and the workshop isn't that great, mostly copy/pasting.

**Comment by f-tsang** [comment]
Yes please to generators! It'd be a good idea to understand JS's version of coroutines/goroutines.

**Comment by lrlna** [comment]
Poll! https://twitter.com/nodeschoolyvr/status/695439235499732994

**Comment by lvivier** [comment]
@lrlna React wins! You wanna tweet out [the ti.to url](https://ti.to/nodeschool-vancouver/2016-02-20)?! :D

**Comment by lrlna** [comment]
done! @lvivier

**Comment by JimFung** [comment]
There are 2 react workshops, learnyoureact and thinking-in-react. Having done a few exercises from learnyoureact I can say i didn't learn much and wouldn't recommend it.

**Comment by lvivier** [comment]
@JimFung is there another online source for learning React that you'd recommend instead? We don't have to use the official workshoppers if they aren't up to scratch!

**Comment by JimFung** [comment]
@lvivier I haven't really looked at other resources. I know that react [wiki](https://github.com/facebook/react/wiki/Examples) has some cool examples, but they aren't really in tutorial form. I'm going to try and find some time to step through thinking-in-react. I've read through the lessons in the repo and they seem like they're structured better (ie. shows you a small code example and then asks you to write something, versus copy/pasting like in learnyoureact).
