### ISSUE TITLE
April 30th 2016 NodeSchool

### ISSUE THREAD

**Issue by lvivier** [nodeschool/vancouver#33]
Hi everyone! Let's schedule an **April NodeSchool** :school: :sunny: !

cc @lrlna, @qard, @switters, @tabruhn, @forivall, @florida, @normful
## When & Where

Zillow
#460 - 1122 Mainland St

Vancouver BC

April 30th, 2016 12-5pm
## Tasks
- [x] Date and venue
- [ ] Call for mentors
- [x] Decide on a theme :speaker::notes: _WebAudio_ :speaker::notes:
- [x] Set up [ti.to](https://ti.to/) event ([here](https://ti.to/nodeschool-vancouver/2016-04-30))
- [x] Add event to nodeschool.io
- [x] Update README.md
- [x] Update gh-pages
- [ ] Send a message to mailing list
- [x] Tweet about the upcoming event

**Comment by Qard** [comment]
:tada: Anyone up for audio hacking fun?

**Comment by lrlna** [comment]
OMG YAY! Sign me up for some web :musical_note: audio :musical_note: <3

I am still in Uruguay on the 23rd, but I am around on the 30th. However, don't let me stop you from having it on the 23rd.

**Comment by Qard** [comment]
I'm good with either.

**Comment by JimFung** [comment]
Should we recommend that attendees should bring a pair of earphones this time?

**Comment by lvivier** [comment]
:speaker: Yes to audio! Let's make it the 30th, gives us more time to get ready too.

**Comment by Qard** [comment]
Should probably run through the [web-audio-school](https://github.com/mmckegg/web-audio-school) workshopper and make sure it's all working as expected.

**Comment by Schoonology** [comment]
It looks like I can be there. (Thanks to @Qard for the invite!) Would mentorship be useful, or do we have an abundance?

**Comment by lvivier** [comment]
@Schoonology we're always looking for more mentors!

**Comment by lvivier** [comment]
@lrlna want to send out some Twitter buzz about the event? Ti.to link is https://ti.to/nodeschool-vancouver/2016-04-30

**Comment by lrlna** [comment]
@lvivier anddddd done: https://twitter.com/nodeschoolyvr/status/718838090157019136

**Comment by Schoonology** [comment]
Looks like I'm running late. Since I've never been, what's the parking situation? Just street parking?

**Comment by lvivier** [comment]
@Schoonology parking on Mainland Street is pretty expensive, and unfortunately our building has no short-term spots. I usually park under the Urban Fare at Davie south of Pacific, $9 all day.

**Comment by Qard** [comment]
There's lots of street parking in the area. Not sure how much is pay parking though. I just take the Skytrain there, so I've never paid much attention to the parking situation.

**Comment by Schoonology** [comment]
Buzzing #460 leads to voicemail. Can buzz me in?

**Comment by lvivier** [comment]
Another NodeSchool done! Thanks to everyone who came out. We'll see you in May!
