### ISSUE TITLE
NodeSchool International Day 2016?

### ISSUE THREAD

**Issue by lvivier** [nodeschool/vancouver#34]
It's almost time for the big NodeSchool: [International Day](http://nodeschool.io/international-day/)!

This year it's on **Saturday, May 21st**. Unfortunately I have a wedding to attend, so I can't make it. Does anyone have a lead on an **alternate venue** in case nobody from Zillow is available?
## When & Where

???

May 21st, 2016 12-4pm
## Tasks
- [ ] Decide on a venue
- [ ] Call for mentors
- [ ] Decide on a theme
- [ ] Set up [ti.to](https://ti.to/) event ([here](https://ti.to/nodeschool-vancouver/2016-04-30))
- [ ] Add event to nodeschool.io
- [ ] Update README.md
- [ ] Update gh-pages
- [ ] Send a message to mailing list
- [ ] Tweet about the upcoming event

**Comment by JimFung** [comment]
I can get in touch with the some people at UBC to see if they can open up some rooms for us. This will probably mean an influx of UBC students at the event. 

EDIT: by 'some people', I mean the people in charge of the co-op program for computer science at UBC.

**Comment by lvivier** [comment]
cc @JimFung @lrlna @qard @switters @tabruhn @forivall @florida @normful @xer0x @sintaxi 

Who's interested in organizing an **International Day** event? I think there's still enough time to plan one. I can help coordinate things, but I won't be available on the day.

**Comment by lrlna** [comment]
Hey! I can help organize. I am not sure where to host though. I don't think UBC is a viable option (it's really far!) Errrr anyone know of a place, or can volunteer their office?

**Comment by JimFung** [comment]
UBC is quite far away :cry: I emailed them last week about using a few rooms and they haven't gotten back to me. I can poke them again about it if we don't find another space to use.

**Comment by lrlna** [comment]
I think I'll tweet we need a space.

**Comment by lrlna** [comment]
ok tweeted! https://twitter.com/nodeschoolyvr/status/728966491517816832

**Comment by kennethormandy** [comment]
- Unbounce near the downtown library is our current venue for [Type Brigade](http://typebrigade.com), and they make it really easy to book their space: http://unbounce.com/event-space/
- We hold special events at CodeCore in Gastown, email me if you need an introduction to someone there, although I imagine you also know people
- Mobify in Yaletown, don’t have a specific contact there now but contact@mobify.com or @mobifycareers
- Regarding schools, I can’t speak to UBC specifically, but I know Emily Carr required insurance of some kind to hold any kind of non-official external event there. I think you could ask the VanJS team if you wanted a contact at the SFU campus, but I believe they pay for space their as well.

**Comment by lvivier** [comment]
Cameron from Decentral Van has [offered us space there on Twitter](https://twitter.com/Amble_Greene/status/730346697650524160).

**Comment by lrlna** [comment]
cool! Okay, 21st is this saturday O.O I should get on this a little better. @lvivier could you set up ti.to for us? I will get to spreading the word out.

**Comment by lvivier** [comment]
Closed for #35
