### ISSUE TITLE
May NodeSchool! 

### ISSUE THREAD

**Issue by lrlna** [nodeschool/vancouver#35]
✨ folks! ✨  Let's schedule a May NodeSchool 🏫  ☀️  !

This is International NodeSchool Day, so it's a big one!

cc @lvivier, @qard, @switters, @tabruhn, @forivall, @florida, @normful
## When & Where

Decentral Van -- 436 W Pender

May 21st, 2016 13-5pm
## Tasks
- [x] Date and venue DecentralVan
- [x] Call for mentors
- [x] Decide on a theme!! -- It seems ✨ electorn ✨ is winning
- [x] Set up ti.to event (https://ti.to/nodeschool-vancouver/2016-05-21)
- [x] Add event to nodeschool.io
- [x] Add event to International nodeschool.io
- [x] Update README.md -- see [pull request](https://github.com/nodeschool/vancouver/pull/36)
- [x] Update gh-pages
- [ ] Send a message to mailing list
- [x] [Tweet](https://twitter.com/nodeschoolyvr/status/732754227420749825) about the upcoming event

**Comment by lrlna** [comment]
Feedback that would be awesome today is about the actual theme. A few that I liked off the website and was going to run a poll on twitter:
1. Bytwiser
2. Electron
3. Hapi.js 

Whatcha think?

**Comment by Qard** [comment]
1 vote for Electron from me.

**Comment by willhoag** [comment]
I voted Hapi.js on Twitter, but was a toss up between that and Electron for me. So, I'm game for whichever. Also, my schedule finally free'd up a bit, so if there is any delegate-able tasks floating around out there, let me know.

**Comment by lrlna** [comment]
I just need the ti.to event set up right now, I think @willhoag ! I don't have access to our ti.to page :|

/cc @lvivier

**Comment by lrlna** [comment]
OOOO would anyone be interested in doing a lightning talk (5-10min) on something cool they are doing with node?!? Since it's a International Nodeschool day?? Something special??  /cc @willhoag @Qard maybe?!?! We could do 1 or 2 of these?

BTW, this is my last Vancouver Nodeschool for a while 😢 , I am moving at the end of the month 😢

**Comment by willhoag** [comment]
I don't have anything cool I'm doing with node ATM, unfortunately. Sorry to hear you are leaving – hope it's to somewhere fun!

**Comment by lvivier** [comment]
@lrlna I invited you and @Qard to the admin team on ti.to, I'll try and get the event set up right away tho

**Comment by lrlna** [comment]
Brilliant! Thanks @lvivier ^.^

decentral van is asking for us to do it at 1 or 2 instead of 12, apparently
they have something running in the morning already... Thoughts on this?

**Comment by lvivier** [comment]
Ti.to event is here: https://ti.to/nodeschool-vancouver/2016-05-21

Still needs:
- Decentral Vancouver address
- Map update
- International Day-specific blurb
- Go Live!

**Comment by lvivier** [comment]
Should also add Vancouver to the International Day website: http://nodeschool.io/international-day/

**Comment by lrlna** [comment]
gonna enroll us!

**Comment by lrlna** [comment]
Y'all I am going to make an executive decision and move our nodeschool to 1pm instead of 12. I don't think there is time to look for another place that could host us at 12 😢

**Comment by lrlna** [comment]
Thanks for coming everyone!! Until next time 🎉 👯
