### ISSUE TITLE
June 25th 2016 NodeSchool

### ISSUE THREAD

**Issue by lvivier** [nodeschool/vancouver#39]
cc @gyaresu @lrlna @qard @switters @tabruhn @forivall @florida @normful @baldwynn

Time to plan a **June NodeSchool**!
## When & Where

June 25, 12-4pm

> Zillow HQ
> # 460 - 1122 Mainland St
> 
> Vancouver BC
> buzz **#460** for entry
## Tasks
- [x] Date and venue
- [ ] Call for mentors
- [x] Decide on a theme!! **WebGL**
- [x] Set up ti.to event (https://ti.to/nodeschool-vancouver/2016-06-25)
- [x] Add event to nodeschool.io
- [x] Update README.md
- [ ] Update `gh-pages` branch
- [ ] Send a message to mailing list
- [x] Tweet about the upcoming event

**Comment by Qard** [comment]
Anyone interested in doing WebGL stuff this time around?

**Comment by forivall** [comment]
Sounds good to me! Lets just make sure that the workshopper is quality. 😔

**Comment by JimFung** [comment]
there seems to be 2 webgl workshops, they're both pretty old

**Comment by gyaresu** [comment]
I get back to Canada the following day :(

**Comment by Qard** [comment]
@lvivier Any chance we could move it to the next weekend?

**Comment by lvivier** [comment]
@gyaresu @Qard yeah, let's do it the 25th instead!

**Comment by lvivier** [comment]
@Qard @JimFung did those WebGL workshoppers turn out to be any good? Sounds like a cool theme to me

**Comment by Qard** [comment]
Haven't had time to check yet. I'm rather busy until Thursday.

**Comment by JimFung** [comment]
I think I have some time tomorrow to work through some of them. I'll keep you posted.

**Comment by lrlna** [comment]
Awww y'all have fun without me <3 <3

**Comment by lvivier** [comment]
@lrlna Twitter account is suffering, we (I) lack your emoji skills haha 🍧 😕

**Comment by gyaresu** [comment]
Guess who's had to cancel his ticket home and is now going to be doing two more countries over the next three weeks...

So sorry to miss this month. I was REALLY looking forward to it. Fingers crossed for next month.

**Comment by JimFung** [comment]
So there are 2 webgl related workshops, [webgl-workshope](https://github.com/stackgl/webgl-workshop) and [IntroToWebGLWithThreeJS](https://github.com/alexmackey/IntroToWebGLWithThreeJS). They haven't been updated in a while, but they are pretty well written. 

The webgl-workshop is similar to the web audio workshopper we did a few nodeschools ago where everything is done in the browser. It doesn't work on node 5.0 and above though, so we'll have to nvm down to 4.1.2 to use it. The other workshop is like the regular nodeschool workshops, but it doesn't have any validation. Instead it says "if you see something, its working". It is also teaching you more about Three.JS library instead of the WebGL API. I think it'd be nice to work through but if I was to pick on to learn about WebGL I'd pick the first guy and work through the Three.JS one after so I understand whats actually going on under the hood.

@gyaresu Have a safe trip!

**Comment by lvivier** [comment]
@JimFung thanks for the summary! @gyaresu we'll miss you, but have a good extended tour!

**Comment by lvivier** [comment]
NodeSchool complete! This was a fun one, thanks everyone for attending and special thanks to all the mentors.
