### ISSUE TITLE
Housekeeping

### ISSUE THREAD

**Issue by lvivier** [nodeschool/vancouver#40]
I'm going to create a `vancouver` team for the nodeschool org on GitHub, so I'm not the bottleneck on administration and event planning. **Organizer volunteers needed**!
## Tasks
- [x] Create a `vancouver` team on nodeschool
- [x] Add organizers to the team
- [x] Add organizers to ti.to
- [x] Simplify our README.md
- [x] Update our [chapters file](https://github.com/nodeschool/nodeschool.github.io/blob/source/chapters/vancouver.json)
- [x] Update the info on our website

**Comment by Qard** [comment]
I'm always happy to help however I can! 😸

**Comment by lvivier** [comment]
@nodeschoolbot add-user qard

**Comment by nodeschoolbot** [comment]
I have added @qard to the `chapter-organizers` team.

**Comment by lvivier** [comment]
@nodeschoolbot add-team-user vancouver qard

**Comment by nodeschoolbot** [comment]
I have invited @qard to the `vancouver` team.

**Comment by nodeschoolbot** [comment]
I have encountered an error doing this :(

```
Error: Bad status: 404
    at Request._callback (/home/maf/versions/nodeschoolbot-1459187320367/node_modules/nodeschoolbot/bin.js:266:50)
    at Request.self.callback (/home/maf/versions/nodeschoolbot-1459187320367/node_modules/nodeschoolbot/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/maf/versions/nodeschoolbot-1459187320367/node_modules/nodeschoolbot/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/maf/versions/nodeschoolbot-1459187320367/node_modules/nodeschoolbot/node_modules/request/request.js:963:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
```
