### ISSUE TITLE
September NodeSchool?

### ISSUE THREAD

**Issue by lvivier** [nodeschool/vancouver#43]
cc @gyaresu @lrlna @qard @switters @tabruhn @forivall @florida @normful @baldwynn @JimFung 

Anybody interested in running a September NodeSchool 🎒? What weekends do we all have free these days? **Update** September 25th
## When & Where

Sunday September 25, 12-4pm

> Zillow HQ
> # 460 - 1122 Mainland St
> 
> Vancouver BC
> buzz **#460** for entry
## Tasks
- [x] Date and venue
- ~~Decide on a theme!!~~ _we'll do it live_
- [ ] Call for mentors
- [x] Set up ti.to event (https://ti.to/nodeschool-vancouver/2016-09-25)
- [x] Add event to nodeschool.io
- [ ] Send a message to mailing list
- [x] Tweet about the upcoming event

**Comment by lrlna** [comment]
I am sorry folks, I am still in London :| Y'all have fun without me ✨

**Comment by gyaresu** [comment]
I am Turkey/Israel until the 18th so I want to say anytime after that but I also might be staying longer. Won't know for at least a week.

But I _**miss**_ nodeschool!

**Comment by JimFung** [comment]
I'll be in NYC from the 10th to the 18th, but I'll be free to help after that! :smiley:

**Comment by Qard** [comment]
I'm available whenever. (Unemployment, yay?)

Sounds like something after the 18th would be the best timing.

**Comment by lvivier** [comment]
Okay, how about the 24th or 25th then?

**Comment by aaron-price** [comment]
I could make it on the 25th, or most Sundays. But not Saturdays.

**Comment by lvivier** [comment]
OK, 25th. Let me try and set something up for then. Anyone have ideas for a theme? Or better yet, anyone want to do a short 5-8 min talk on an intro node.js topic?

**Comment by liline** [comment]
25th works for me

**Comment by rcass** [comment]
Just wondering if this happening?  I am not interested in running but I would love to attend!

**Comment by lvivier** [comment]
@rcass it's still happening!! I'm getting all the event registration stuff straightened out now and I'll update here when it's ready to go

**Comment by lvivier** [comment]
Finally some event stuff:
- [NodeSchool event signup](https://ti.to/nodeschool-vancouver/2016-09-25)
- [pls retweet](https://twitter.com/nodeschoolyvr/status/778289873140625408)

**Comment by Qard** [comment]
Do we _need_ a theme this time? I'm thinking since we're just getting it started back up again we can probably keep it simple this time around.

**Comment by lvivier** [comment]
@Qard that sounds good to me

**Comment by gyaresu** [comment]
How many folks got the Tessel? I never ended up receiving mine but if there are a few then maybe there's some Nodebots fun to be had?

That and the 'Fun-damentals' big room for new folks?

**Comment by Qard** [comment]
I've got mine. I also got a Photon sample pack from nexxy at CascadiaFest. 😸

**Comment by gyaresu** [comment]
And as usual it would be great to reach out to the LLC mob. Continue our mission of making a safe friendly learning environment for folks.

**Comment by aaron-price** [comment]
So funny story... Got all the way to waterfront and realized I forgot my laptop in Coquitlam. Like a noob. Really sorry about this, but I won't be making it today :-(

**Comment by lvivier** [comment]
@aaron-price oh no! bummer! well, now you gotta come to the next one, right? :D

**Comment by lvivier** [comment]
Thanks for coming everyone, we'll announce an October NodeSchool soon!
