### ISSUE TITLE
October 29th 2016 NodeSchool

### ISSUE THREAD

**Issue by lvivier** [nodeschool/vancouver#45]
cc @gyaresu @lrlna @qard @switters @tabruhn @forivall @florida @normful @baldwynn @JimFung

Let's keep the ball rolling and schedule an October NodeSchool!

▶️ **[Sign up here](https://ti.to/nodeschool-vancouver/2016-10-29)** ◀️ 
## Tasks
- [x] Date **October 29**
- [x] Venue **Lighthouse Labs**
- [x] Call for a ⚡lightning talk⚡
- [x] Call for mentors
- [x] Set up [ti.to event](https://ti.to/nodeschool-vancouver/2016-10-29)
- [x] Add event to nodeschool.io
- [ ] Send a message to mailing list
- [x] Tweet about the upcoming event

**Comment by JimFung** [comment]
FYI Digital Ocean is also running Hacktoberfest again this year for the month of October if some people want to show up to work on OSS together. 
https://hacktoberfest.digitalocean.com/

**Comment by JimFung** [comment]
I vote for the 22nd or 29th!

**Comment by lvivier** [comment]
OK, looks like we're going to have our next event on the 29th at [Lighthouse Labs](https://www.lighthouselabs.ca/vancouver) in Gastown. Who's interested in mentoring or perhaps giving a short 5-8 minute ⚡️ talk on a beginner node.js topic?

**Comment by forivall** [comment]
I feel like I could give a talk on understanding the event loop, since I kinda did that at the end of last nodeschool 😰

**Comment by Qard** [comment]
I'd be happy to do a quick talk on the difference between callbacks and asynchrony.

**Comment by donburks** [comment]
Just wanted to chime in and welcome NodeSchool to Lighthouse Labs. I am looking forward to the event.

**Comment by lrlna** [comment]
awwww y'all finally decided on doing lightning talks <3 ✨ that makes me super happy ✨

**Comment by lvivier** [comment]
Signup is ready, link in the issue description!

**Comment by lvivier** [comment]
Hi everyone, just a reminder that NodeSchool will be at **Lighthouse Labs** tomorrow @ noon! See you there!
