### ISSUE TITLE
November/December 2016 NodeSchool

### ISSUE THREAD

**Issue by lvivier** [nodeschool/vancouver#48]
cc mentors: @gyaresu @lrlna @qard @switters @tabruhn @forivall @florida @normful @baldwynn @JimFung @donburks

Hi all, I'm not going to be able to help with NodeSchool in November or December. Does anyone want to take the reins and organize an event? I believe @qard has admin privileges on ti.to and access to the Twitter account.

## Tasks

- [ ] Date
- [ ] Venue
- [ ] Call for a ⚡lightning talk⚡
- [ ] Call for mentors
- [ ] Set up ti.to event
- [ ] Add event to nodeschool.io
- [ ] Send a message to mailing list
- [ ] Tweet about the upcoming event

**Comment by Qard** [comment]
I can help out with that, though I might not have much time since I'll be at Node Interactive next week.

@donburks Can we borrow the Lighthouse Labs space again?

**Comment by donburks** [comment]
Yes, we would love to host you again. Let me know what dates you are
thinking of. There are a few events we have in the first two weeks of
December, but we will do our best to make it work for you.

http://www.lighthouselabs.ca/

_Don Burks_
Head Instructor
_Telephone:_ +1 778 235 4334 <//+17782354334>
_Website:_ www.lighthouselabs.ca

_Learn how
https://lighthouselabs.ca/blog/our-education-philosophies?utm_source=signature&utm_medium=email&utm_campaign=emlsig
we help create amazing developers._

On Mon, Nov 21, 2016 at 11:01 AM, Stephen Belanger <notifications@github.com

**Comment by Qard** [comment]
Saturdays/Sundays are ideal, but I'm good with evenings too. I'm fine with anything that is available, other than November 28th though December 3rd as I'll be in Austin for Node Interactive and the following Collaborator Summit. Not sure how many people would show up closer to the holidays though.

**Comment by JimFung** [comment]
It's finals season so I might not show up because I've got to study but I'll try to make it work with whatever day you guys end up picking.

**Comment by donburks** [comment]
We have December 3rd, 4th, and 11th, with the 3rd being the best date for
us.

http://www.lighthouselabs.ca/

_Don Burks_
Head Instructor
_Telephone:_ +1 778 235 4334 <//+17782354334>
_Website:_ www.lighthouselabs.ca

_Learn how
https://lighthouselabs.ca/blog/our-education-philosophies?utm_source=signature&utm_medium=email&utm_campaign=emlsig
we help create amazing developers._

**Comment by Qard** [comment]
I won't be back in town until the evening of the 3rd, so either the 4th or 11th would be good. Whichever is better for you.

**Comment by donburks** [comment]
I missed this message entirely, somehow. We could do the 11th. The 4th would be difficult to have someone here the whole day.

**Comment by JimFung** [comment]
Guess this kinda fell through guys, It is the holidays so I suppose turnout would be low anyways as people would want to spend time with their friends/family. Lets try again in January! 

Happy Holidays guys! 🎅 🎄 ❄️

**Comment by Qard** [comment]
Yeah, I just didn't have enough time to keep things moving after being out of town at Node Interactive for the first week of December. I expect things should pick up again in January though.

**Comment by lvivier** [comment]
Hey team, I'm back from my road trip and Christmas. I'll make a January issue and we can go from there!
