### ISSUE TITLE
January 2017 NodeSchool

### ISSUE THREAD

**Issue by lvivier** [nodeschool/vancouver#49]
cc mentors: @gyaresu @lrlna @qard @switters @tabruhn @forivall @florida @normful @baldwynn @JimFung @donburks

New year, new school! 🎉 🍾 

## Tasks

- [x] Date
- [x] Venue **Lighthouse Labs**
- [ ] Call for a ⚡lightning talk⚡
- [ ] Call for mentors
- [x] Set up ti.to event
- [x] Add event to nodeschool.io
- [ ] Send a message to mailing list
- [x] Tweet about the upcoming event

**Comment by donburks** [comment]
Venue is not an issue. Lighthouse is happy to sponsor with venue. I'll
mentor as well.


<http://www.lighthouselabs.ca/>

*Don Burks*
Head Instructor
*Telephone:* +1 778 235 4334 <//+17782354334>
*Website:* www.lighthouselabs.ca

*Learn how
<https://lighthouselabs.ca/blog/our-education-philosophies?utm_source=signature&utm_medium=email&utm_campaign=emlsig>
we help create amazing developers.*

**Comment by Qard** [comment]
As always, I'm happy to help out in any way I can.

So Lighthouse again? What day do we want to aim for?

**Comment by kc-dot-io** [comment]
I'd love to get in on some mentoring if you'll have me.

**Comment by JimFung** [comment]
Down to help out!

**Comment by lvivier** [comment]
All right! How does Saturday 21st work for everyone?

**Comment by donburks** [comment]
Would it be possible to do Sunday the 22nd instead? There is a Young Entrepreneurs event at Launch Academy on the 21st, which may cause some space constraints.

**Comment by Qard** [comment]
No problem with Sunday for me. Anyone else?

**Comment by JimFung** [comment]
The 22nd works for me as well.

**Comment by donburks** [comment]
We have rooms booked here at Lighthouse for January 22nd from Noon to 5pm.
Feel free to advertise!


<http://www.lighthouselabs.ca/>

*Don Burks*
Head Instructor
*Telephone:* +1 778 235 4334 <//+17782354334>
*Website:* www.lighthouselabs.ca

*Learn how
<https://lighthouselabs.ca/blog/our-education-philosophies?utm_source=signature&utm_medium=email&utm_campaign=emlsig>
we help create amazing developers.*

**Comment by Qard** [comment]
Looks like Luke will be away that weekend, but he says he's good with missing this time.

**Comment by JimFung** [comment]
Do we want to pick a theme? also is anyone interested in doing a lightning talk?

**Comment by Qard** [comment]
FYI, I forgot to edit the time from the previous listing, so the ti.to says it starts at 1PM rather than noon. If anyone is there early, you could help get set up, I guess.
