### ISSUE TITLE
February 2017 NodeSchool

### ISSUE THREAD

**Issue by Qard** [nodeschool/vancouver#50]
cc mentors: @lvivier @gyaresu @lrlna @switters @tabruhn @forivall @florida @normful @baldwynn @JimFung @donburks

Let's get this rolling...

@donburks Can we use Lighthouse Labs again? When is a good time?

## Tasks

- [x] Date
- [x] Venue **Lighthouse Labs**
- [ ] Theme?
- [ ] Call for a ⚡lightning talk⚡
- [x] Call for mentors
- [x] Set up ti.to event
- [x] Add event to nodeschool.io
- [x] Tweet about the upcoming event

**Comment by donburks** [comment]
Definitely happy to be host again. Let me know what dates look likely. I am
away this weekend, but back next week, and then away most weekends in
March. My presence isn't 100% necessary to use the space, but we would need
to recruit another mentor from LHL to play host. (Site rules)


<http://www.lighthouselabs.ca/>

*Don Burks*
Head Instructor
*Telephone:* +1 778 235 4334 <//+17782354334>
*Website:* www.lighthouselabs.ca

*The HTML500 is bringing free coding education to 9 Canadian
cities! Register here
<http://www.thehtml500.com/?utm_campaign=signature&utm_medium=referral&utm_source=email>.*

**Comment by Qard** [comment]
Does Saturday the 25th work?

**Comment by lvivier** [comment]
Works for me! Thanks for taking the lead @Qard. I'm moving to Vancouver Island at the end of February, so my presence at NodeSchool Van will be sporadic from now on…

**Comment by donburks** [comment]
The 25th works great for Lighthouse, as long as we are starting at 1pm.
Launch Academy is having an event until 12:30. It will take a few minutes
for everyone to trickle out and to reset the space.


<http://www.lighthouselabs.ca/>

*Don Burks*
Head Instructor
*Telephone:* +1 778 235 4334 <//+17782354334>
*Website:* www.lighthouselabs.ca

*The HTML500 is bringing free coding education to 9 Canadian
cities! Register here
<http://www.thehtml500.com/?utm_campaign=signature&utm_medium=referral&utm_source=email>.*

**Comment by Qard** [comment]
Saturday it is. 1PM to 5PM sound good?

**Comment by JimFung** [comment]
I'll try to make it and actually be helpful this time!

**Comment by lvivier** [comment]
Sorry for missing this one, y'all. I ended up moving on the 25th instead of the 28th. How did it go?

**Comment by Qard** [comment]
It went alright. There was some confusion about the space, but we got in okay. Not a very big crowd this time around though, only about 10 of us.
